#!/usr/bin/env python3
"""Render the RAG control catalogue from YAML into audit-ready Markdown.

`controls/controls.yaml` is the single source of truth; this tool renders from it and never
the other way round. `catalogue` writes the Prüfkatalog (every control with Kontrollziel,
Prüfhandlung, Evidenz-Artefakt and Mapping); `readiness` writes a report for one assessment
(green/yellow/red, open Auflagen, deadlines); `check` fails if a rendering has drifted.

    python tools/render_controls.py catalogue
    python tools/render_controls.py readiness --assessment pilot/controls-assessment.yaml
    python tools/render_controls.py check --assessment pilot/controls-assessment.yaml
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parent.parent
CONTROLS = ROOT / "controls" / "controls.yaml"
CATALOGUE = ROOT / "controls" / "controls.md"

REQUIRED = ("title", "objective", "audit_procedure", "evidence", "mapping")
STATUS = {
    "green": ("🟢", "erfüllt"),
    "yellow": ("🟡", "teilweise erfüllt — Auflage"),
    "red": ("🔴", "nicht erfüllt — Auflage"),
}
BANNER = "<!-- generated by tools/render_controls.py from controls/controls.yaml — do not edit -->"
MAPPING_LABELS = (
    ("dora", "DORA"),
    ("marisk", "MaRisk"),
    ("bait", "BAIT (historisch)"),
    ("dsgvo", "DSGVO"),
    ("generic", "Generisch"),
)


def load(path: Path) -> dict[str, Any]:
    with path.open(encoding="utf-8") as fh:
        return yaml.safe_load(fh)


def validate(doc: dict[str, Any]) -> list[str]:
    """Return a list of schema violations. Empty list means the catalogue is well-formed."""
    errors: list[str] = []
    domains = {d["id"] for d in doc.get("domains", [])}
    seen: set[str] = set()
    for control in doc.get("controls", []):
        cid = control.get("id", "<no id>")
        if cid in seen:
            errors.append(f"{cid}: duplicate control id")
        seen.add(cid)
        for field in REQUIRED:
            value = control.get(field)
            if not value:
                errors.append(f"{cid}: missing mandatory field '{field}'")
        if control.get("domain") not in domains:
            errors.append(f"{cid}: unknown domain '{control.get('domain')}'")
    if not doc.get("controls"):
        errors.append("no controls defined")
    return errors


def _mapping_lines(mapping: dict[str, list[str]]) -> list[str]:
    return [
        f"  - *{label}:* " + "; ".join(mapping[key])
        for key, label in MAPPING_LABELS
        if mapping.get(key)
    ]


def render_catalogue(doc: dict[str, Any]) -> str:
    meta = doc.get("meta", {})
    by_domain: dict[str, list[dict[str, Any]]] = {}
    for control in doc["controls"]:
        by_domain.setdefault(control["domain"], []).append(control)

    out = [
        BANNER,
        "",
        "# Prüfkatalog — Kontrollen für RAG-Systeme im regulierten Umfeld",
        "",
        meta.get("intro", ""),
        "",
        f"**Stand:** {meta.get('updated', 'n/a')} · **Version:** {meta.get('version', 'n/a')} · "
        f"**{len(doc['controls'])} Kontrollen** in {len(doc['domains'])} Domänen",
        "",
        "> **Kein Rechtsrat.** Dieser Katalog ist ein Arbeitsmittel, kein Nachweis der Erfüllung "
        "regulatorischer Anforderungen. Siehe `DISCLAIMER.md`.",
        "",
        "## Überblick",
        "",
        "| ID | Kontrolle | Domäne | Evidenz |",
        "|---|---|---|---|",
    ]
    domain_names = {d["id"]: d["name"] for d in doc["domains"]}
    for control in doc["controls"]:
        evidence = ", ".join(control["evidence"])
        out.append(
            f"| `{control['id']}` | {control['title']} | "
            f"{domain_names[control['domain']]} | {evidence} |"
        )
    out.append("")

    for domain in doc["domains"]:
        controls = by_domain.get(domain["id"], [])
        if not controls:
            continue
        out += [f"## {domain['id']} — {domain['name']}", "", domain.get("description", ""), ""]
        for control in controls:
            out += [
                f"### `{control['id']}` {control['title']}",
                "",
                f"**Kontrollziel.** {control['objective']}",
                "",
                f"**Prüfhandlung.** {control['audit_procedure']}",
                "",
                "**Evidenz-Artefakt.**",
            ]
            out += [f"- {item}" for item in control["evidence"]]
            out += ["", "**Mapping.**"]
            out += _mapping_lines(control["mapping"])
            if control.get("note"):
                out += ["", f"**Hinweis.** {control['note']}"]
            out.append("")

    out += ["## Offene Punkte", ""]
    out += [f"- {item}" for item in meta.get("open_questions", ["—"])]
    return "\n".join(out) + "\n"


def render_readiness(doc: dict[str, Any], assessment: dict[str, Any]) -> str:
    controls = {c["id"]: c for c in doc["controls"]}
    results = assessment.get("results", [])
    counts = {key: sum(1 for r in results if r.get("status") == key) for key in STATUS}
    unassessed = [cid for cid in controls if cid not in {r["control"] for r in results}]
    meta = assessment.get("meta", {})

    out = [
        BANNER,
        "",
        f"# Readiness-Report — {meta.get('system', 'RAG-System')}",
        "",
        f"**Institut:** {meta.get('institution', 'n/a')} · **Stand:** {meta.get('date', 'n/a')} · "
        f"**Bewertet durch:** {meta.get('assessor', 'n/a')}",
        "",
        meta.get("note", ""),
        "",
        "## Ergebnis",
        "",
        "| Status | Anzahl |",
        "|---|---|",
    ]
    for key, (icon, label) in STATUS.items():
        out.append(f"| {icon} {label} | {counts[key]} |")
    out.append(f"| ⚪ nicht bewertet | {len(unassessed)} |")
    out += [
        "",
        f"**Freigabeempfehlung:** {meta.get('recommendation', 'offen')}",
        "",
        "## Kontrollen im Einzelnen",
        "",
        "| Kontrolle | Status | Befund | Auflage | Frist |",
        "|---|---|---|---|---|",
    ]
    for result in results:
        control = controls.get(result["control"])
        if control is None:
            continue
        icon, _ = STATUS.get(result.get("status", ""), ("⚪", "nicht bewertet"))
        out.append(
            f"| `{result['control']}` {control['title']} | {icon} | "
            f"{result.get('finding', '—')} | {result.get('auflage', '—')} | "
            f"{result.get('due', '—')} |"
        )
    out.append("")

    open_items = [r for r in results if r.get("status") in ("yellow", "red")]
    if open_items:
        out += ["## Auflagen", ""]
        for result in open_items:
            icon, _ = STATUS[result["status"]]
            out += [
                f"### {icon} `{result['control']}` — {controls[result['control']]['title']}",
                "",
                f"**Befund.** {result.get('finding', '—')}",
                "",
                f"**Auflage.** {result.get('auflage', '—')}",
                "",
                f"**Frist.** {result.get('due', '—')} · "
                f"**Verantwortlich.** {result.get('owner', '—')}",
                "",
            ]
    if unassessed:
        out += ["## Nicht bewertet", "", ", ".join(f"`{c}`" for c in unassessed), ""]
    return "\n".join(out)


def write(path: Path, content: str, check: bool) -> bool:
    """Write `content` to `path`, or in check mode report whether it is already current."""
    full = path.resolve()
    name = full.relative_to(ROOT) if full.is_relative_to(ROOT) else full
    current = full.read_text(encoding="utf-8") if full.exists() else None
    if check:
        if current != content:
            print(f"✗ {name} is out of date — run render_controls.py")
            return False
        print(f"✓ {name} is current")
        return True
    full.write_text(content, encoding="utf-8")
    print(f"✓ wrote {name}")
    return True


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("command", choices=("catalogue", "readiness", "check"))
    parser.add_argument("--controls", type=Path, default=CONTROLS)
    parser.add_argument("--assessment", type=Path, help="assessment YAML for the readiness report")
    parser.add_argument("--out", type=Path, help="override the output path")
    args = parser.parse_args(argv)

    doc = load(args.controls)
    errors = validate(doc)
    if errors:
        listed = "\n".join(f"  - {error}" for error in errors)
        print(f"✗ controls.yaml is invalid:\n{listed}", file=sys.stderr)
        return 1

    check = args.command == "check"
    ok = True
    if args.command in ("catalogue", "check"):
        ok &= write(args.out or CATALOGUE, render_catalogue(doc), check)
    if args.assessment:
        assessment = load(args.assessment)
        out = args.out or args.assessment.parent / "readiness-report.md"
        ok &= write(out, render_readiness(doc, assessment), check)
    elif args.command == "readiness":
        parser.error("readiness needs --assessment")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
