#!/usr/bin/env python3
"""Render and verify the decision records under decisions/.

A decision record answers eighteen questions about one AI use case and, for each, points at the
place in the approval file where the answer actually stands. This tool is what makes that
pointing worth something: `check` resolves every reference — file **and** section — against the
repository and fails when one does not exist. A record cannot claim completeness it does not
have, and a heading renamed three files away turns the gate red.

A step without a source needs a `gap:` instead. Gaps are rendered, counted and never silently
tolerated: the rejected case has four of them, and that is the honest state of a case that ended
before those documents were written. A step that *is* answered but only within a limit carries a
`caveat:` alongside its source — collapsing the two would let "answered with a stated limit" pass
as "answered", which is the sloppiness this tool exists to prevent.

    python tools/render_decision.py render
    python tools/render_decision.py check
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parent.parent
DECISIONS = ROOT / "decisions"
OVERVIEW = DECISIONS / "README.md"
BANNER = "<!-- generated by tools/render_decision.py from decisions/*.yaml — do not edit -->"

STEP_NAMES = 18
DECISIONS_ALLOWED = ("GO", "CONDITIONAL_GO", "KILL")
NATURE_ALLOWED = (
    "hypothetical",
    "reference implementation",
    "illustrative case",
    "personal R&D",
    "production-tested",
)
LEVELS = ("low", "medium", "high", "unacceptable")
QUALITY_KEYS = (
    ("business_value", "Business Value"),
    ("operational_risk", "Operational Risk"),
    ("reversibility", "Reversibility"),
    ("blast_radius", "Blast Radius"),
    ("residual_risk", "Residual Risk"),
)
DECISION_LABEL = {
    "GO": "🟢 GO",
    "CONDITIONAL_GO": "🟡 CONDITIONAL GO",
    "KILL": "🔴 KILL",
}


def slug(heading: str) -> str:
    """GitHub's anchor for a Markdown heading: lowercase, punctuation dropped, spaces hyphenated."""
    text = heading.strip().lower()
    text = re.sub(r"[^\w\s-]", "", text, flags=re.UNICODE)
    return re.sub(r"\s+", "-", text).strip("-")


def anchors(path: Path) -> set[str]:
    """Every anchor GitHub would generate for the headings in one file."""
    found: set[str] = set()
    for line in path.read_text(encoding="utf-8").splitlines():
        match = re.match(r"^(#{1,6})\s+(.*)$", line)
        if match:
            found.add(slug(match.group(2)))
    return found


def resolve(reference: str) -> str | None:
    """Return an error message if the reference does not resolve, else None."""
    file_part, _, anchor = reference.partition("#")
    path = ROOT / file_part
    if not path.is_file():
        return f"file does not exist: {file_part}"
    if anchor and anchor not in anchors(path):
        return f"no such section: {file_part}#{anchor}"
    return None


def load_records() -> list[dict[str, Any]]:
    return [yaml.safe_load(p.read_text(encoding="utf-8")) for p in sorted(DECISIONS.glob("*.yaml"))]


def validate(record: dict[str, Any]) -> list[str]:
    """Structural rules first, then every reference in the record."""
    problems: list[str] = []
    meta = record.get("meta", {})
    rid = meta.get("id", "<no id>")

    for field in (
        "id",
        "system",
        "nature",
        "decision",
        "decided_on",
        "decided_by",
        "expires_on",
        "business_owner",
        "technical_owner",
        "risk_owner",
    ):
        if not meta.get(field):
            problems.append(f"{rid}: meta.{field} is missing")

    if meta.get("decision") not in DECISIONS_ALLOWED:
        problems.append(f"{rid}: decision must be one of {DECISIONS_ALLOWED}")
    if meta.get("nature") not in NATURE_ALLOWED:
        problems.append(
            f"{rid}: nature must be one of {NATURE_ALLOWED} — §13 forbids implying more"
        )

    steps = record.get("steps", [])
    numbers = [s.get("n") for s in steps]
    if numbers != list(range(1, STEP_NAMES + 1)):
        problems.append(f"{rid}: steps must be 1..{STEP_NAMES} in order, found {numbers}")

    for step in steps:
        n = step.get("n")
        has_source, has_gap = bool(step.get("source")), bool(step.get("gap"))
        if has_source == has_gap:
            problems.append(
                f"{rid}: step {n} needs exactly one of source or gap — "
                "an unanswered step is recorded, not bridged"
            )
        if has_source and not step.get("answer"):
            problems.append(f"{rid}: step {n} has a source but no answer")
        if has_gap and step.get("caveat"):
            problems.append(
                f"{rid}: step {n} carries both gap and caveat — a step is either unanswered "
                "or answered within a limit, never both"
            )

    for key, label in QUALITY_KEYS:
        entry = record.get("quality", {}).get(key)
        if not entry:
            problems.append(f"{rid}: quality.{key} is missing — §12 asks for {label}")
            continue
        if entry.get("level") not in LEVELS:
            problems.append(f"{rid}: quality.{key}.level must be one of {LEVELS}")
        if not entry.get("basis"):
            problems.append(f"{rid}: quality.{key} states a level without a basis")

    for reference, where in references(record):
        error = resolve(reference)
        if error:
            problems.append(f"{rid}: {where} — {error}")

    return problems


def references(record: dict[str, Any]) -> list[tuple[str, str]]:
    """Every (reference, location) pair the record makes a claim with."""
    found: list[tuple[str, str]] = []
    if assessment := record.get("meta", {}).get("assessment"):
        found.append((assessment, "meta.assessment"))
    for key, _ in QUALITY_KEYS:
        entry = record.get("quality", {}).get(key) or {}
        if source := entry.get("source"):
            found.append((source, f"quality.{key}"))
    for step in record.get("steps", []):
        if source := step.get("source"):
            found.append((source, f"step {step.get('n')}"))
    for condition in record.get("conditions", []):
        if source := condition.get("source"):
            found.append((source, f"condition {condition.get('id')}"))
    return found


def render(records: list[dict[str, Any]]) -> str:
    lines = [
        BANNER,
        "",
        "# Entscheidungssätze",
        "",
        "Ein Entscheidungssatz beantwortet achtzehn Fragen zu einem Vorhaben und zeigt für jede",
        "auf die Stelle in der Akte, an der die Antwort steht. `tools/render_decision.py check`",
        "löst jede dieser Stellen auf — Datei und Abschnitt. Was hier verlinkt ist, existiert;",
        "sonst wäre das Gate rot.",
        "",
        "Ein Schritt ohne Fundstelle trägt eine Lücke mit Begründung. Der abgelehnte Fall hat",
        "vier davon, weil er endete, bevor diese Dokumente geschrieben wurden. Das wird",
        "ausgewiesen, nicht gefüllt.",
        "",
        "**Fiktive Fälle, realer Ablauf.** Kein Rechtsrat — siehe "
        "[`DISCLAIMER.md`](../DISCLAIMER.md).",
        "",
    ]

    lines += [
        "## Überblick",
        "",
        "| Fall | Entscheidung | Beschlossen | Läuft ab | Belegt | Lücken |",
        "|---|---|---|---|---|---|",
    ]
    for record in records:
        meta, steps = record["meta"], record["steps"]
        gaps = sum(1 for s in steps if s.get("gap"))
        lines.append(
            f"| **{meta['system']}** | {DECISION_LABEL[meta['decision']]} | {meta['decided_on']} "
            f"| {meta['expires_on']} | {len(steps) - gaps}/{len(steps)} | {gaps} |"
        )
    lines.append("")

    for record in records:
        meta = record["meta"]
        lines += [
            f"## {meta['system']}",
            "",
            f"**{DECISION_LABEL[meta['decision']]}** — {meta['decided_by']}. "
            f"Wiedervorlage bzw. Ablauf: {meta['expires_on']}.",
            "",
            f"*{meta['nature']}, {meta['institution']} ist erfunden.*",
            "",
            "| Entscheidungsqualität | Stufe | Grundlage |",
            "|---|---|---|",
        ]
        for key, label in QUALITY_KEYS:
            entry = record["quality"][key]
            lines.append(f"| {label} | **{entry['level']}** | {entry['basis']} |")
        lines += ["", "| # | Schritt | Antwort | Fundstelle |", "|---:|---|---|---|"]
        for step in record["steps"]:
            if step.get("gap"):
                gap = " ".join(step["gap"].split())
                lines.append(f"| {step['n']} | {step['name']} | *Lücke: {gap}* | — |")
            else:
                link = step["source"]
                label = link.split("#", 1)[0].split("/")[-1]
                anchor = link.split("#", 1)[1] if "#" in link else ""
                shown = f"{label}#{anchor}" if anchor else label
                answer = step["answer"]
                if step.get("caveat"):
                    answer += f" *(Grenze: {' '.join(step['caveat'].split())})*"
                lines.append(f"| {step['n']} | {step['name']} | {answer} | [{shown}](../{link}) |")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("command", choices=("render", "check"))
    args = parser.parse_args(argv)

    records = load_records()
    if not records:
        print("no decision records under decisions/", file=sys.stderr)
        return 1

    problems = [p for record in records for p in validate(record)]
    if problems:
        print("decision records do not hold up:", file=sys.stderr)
        for problem in problems:
            print(f"  {problem}", file=sys.stderr)
        return 1

    rendered = render(records)
    if args.command == "check":
        current = OVERVIEW.read_text(encoding="utf-8") if OVERVIEW.is_file() else ""
        if current != rendered:
            print(
                f"stale: {OVERVIEW.relative_to(ROOT)} — run "
                "`python tools/render_decision.py render`",
                file=sys.stderr,
            )
            return 1
        total = sum(len(r["steps"]) for r in records)
        gaps = sum(1 for r in records for s in r["steps"] if s.get("gap"))
        print(
            f"{len(records)} decision records, {total - gaps}/{total} steps evidenced, "
            f"{gaps} recorded gaps, every reference resolves"
        )
        return 0

    OVERVIEW.write_text(rendered, encoding="utf-8")
    print(f"wrote {OVERVIEW.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
